name: Deploy Astro Blog

on:
  push:
    branches:
      - master

  workflow_dispatch:


jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.10.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_PRIVATE_KEY }}


      - name: Add SSH host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H "${{ secrets.DEPLOY_HOST }}" >> ~/.ssh/known_hosts


      - name: Deploy
        run: |
          ssh \
            ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} \
            "deploy"
